name: Enhanced CI/CD Pipeline with Integrated Security & Compliance

permissions:
  security-events: write 

on:
  push:
    branches:
      - main  

jobs:
  build_and_scan:
    runs-on: ubuntu-latest  

    steps:

    - name: Checkout code from repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  

    - name: Set up Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '14'  

    - name: Install npm dependencies
      run: npm install  

    - name: Install SonarQube Scanner
      run: |
        curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
        unzip sonar-scanner.zip -d /opt
        echo "/opt/sonar-scanner-4.6.2.2472-linux/bin" >> $GITHUB_PATH  

    - name: Run SonarQube scan with debugging
      run: |
        sonar-scanner \
          -Dsonar.projectKey=nodejs-project \
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
          -Dsonar.sources=. \
          -X

    - name: Build and push Docker image
      run: |
        docker buildx create --use  
        docker buildx build --platform linux/amd64,linux/arm64 -t myapp:latest .  
        docker tag myapp:latest rtx3osie/myapp:latest  
        docker push rtx3osie/myapp:latest  

    - name: Run Trivy vulnerability scan on Docker image
      uses: aquasecurity/trivy-action@0.20.0
      with:
        image-ref: 'rtx3osie/myapp:latest'  
        format: 'sarif'  
        output: 'trivy-results.sarif'  

    - name: Upload Trivy SARIF Report to GitHub
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'trivy-results.sarif'

    - name: Replace image tag in Kubernetes deployment YAML
      run: |
        sed -i "s|rtx3osie/myapp:PLACEHOLDER|rtx3osie/myapp:latest|" ./kube/deployment.yaml
        cat ./kube/deployment.yaml  



